language: node_js
cache:
  directories:
    - node_modules
node_js:
- v6
- v7
- v8
- v9
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  global:
  - CXX=g++-4.8
  - SENDGRID_KEY=sendgridKey
  - MASTER_KEY=masterKey
  - JWT_SECRET=jwtSecret
